---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore 
summary: Astra 可以从快照或备份还原应用程序配置和永久性存储。永久性存储备份会从对象存储传输，因此从现有备份还原的速度最快。 
---
= 还原应用程序
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra 控制中心可以从快照或备份还原您的应用程序。永久性存储备份和快照会从对象存储传输，因此，从现有快照还原到同一集群的速度比其他方法更快。您可以使用 Astra UI 或 https://docs.netapp.com/us-en/astra-automation-2108/index.html["Astra API"^] 还原应用程序。


NOTE: 如果您使用 Helm 部署应用程序，则 Astra 控制中心需要 Helm 版本 3 。完全支持管理和克隆使用 Helm 3 部署的应用程序（或从 Helm 2 升级到 Helm 3 ）。不支持使用 Helm 2 部署的应用程序。


NOTE: 如果要还原到其他集群，请确保此集群使用相同的永久性卷访问模式（例如 ReadWriteMany ）。如果目标永久性卷访问模式不同，还原操作将失败。

[NOTE]
====
在 OpenShift 集群上创建用于托管应用程序的项目时，系统会为该项目（或 Kubernetes 命名空间）分配一个 SecurityContext UID 。要使 Astra 控制中心能够保护您的应用程序并将应用程序移动到 OpenShift 中的其他集群或项目，您需要添加策略，使应用程序能够作为任何 UID 运行。例如，以下 OpenShift 命令行界面命令会为 WordPress 应用程序授予相应的策略。

`oc new-project WordPress` `oc adm policy add-SCS-to-group anyuid system ： serviceaccounts ： WordPress` `oc adm policy add-SCS-to-user privileged -z default -n WordPress`

====
.步骤
. 单击 * 应用程序 * ，然后单击应用程序的名称。
. 单击 * 数据保护 * 。
. 如果要从快照还原，请保持选中 * 快照 * 图标。否则，请单击 * 备份 * 图标以从备份中还原。
. 单击 * 操作 * 列中要从中还原的快照或备份的下拉列表。
. 单击 * 还原应用程序 * 。
. * 还原详细信息 * ：指定还原的详细信息：
+
** 输入应用程序的名称和命名空间。
+

NOTE: 如果要还原已删除的应用程序，请为该应用程序选择与原始名称不同的名称和命名空间。如果还原的应用程序的名称与删除的应用程序相同，还原操作将失败。

** 选择应用程序的目标集群。
** 单击 * 审阅 * 。


. * 还原摘要 * ：查看有关还原操作的详细信息，然后单击 * 还原 * 。


.结果
Astra 控制中心会根据您提供的信息还原应用程序。


NOTE: 在执行数据保护操作（克隆，备份，还原）并随后调整永久性卷大小后，在 UI 中显示新卷大小之前，最长会有 20 分钟的延迟。数据保护操作将在几分钟内成功完成，您可以使用存储后端的管理软件确认卷大小的更改。
